name: 'Downfall Config'
type: module
description: 'Downfall site configuration'
core: 8.x
package: Downfall
dependencies:
    - node
    - field
    - book
    - taxonomy
    - user
    - field_group
    - entity
    - media_entity
    - media_entity_image
    - video_embed_media
    - video_embed_field
    - ctools
    - entity_browser
    - inline_entity_form
    - entity_browser_entity_form
    - components
    - group
    - gnode
    - rng
    - views_advanced_routing
    - veoa
